{{- if or .Values.secrets.dbDsn .Values.secrets.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alexgo-cloud.fullname" . }}-secrets
type: Opaque
stringData:
  {{- if .Values.secrets.dbDsn }}
  DB_DSN: {{ .Values.secrets.dbDsn | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
{{- end }}
