// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: modules/system/api/rpc/token.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      int32                  `protobuf:"varint,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"` // 1管理员 2会员
	TenantId      int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_modules_system_api_rpc_token_proto_rawDescGZIP(), []int{0}
}

func (x *IssueTokenRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IssueTokenRequest) GetUserType() int32 {
	if x != nil {
		return x.UserType
	}
	return 0
}

func (x *IssueTokenRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *IssueTokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type IssueTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_modules_system_api_rpc_token_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *IssueTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *IssueTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_modules_system_api_rpc_token_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_modules_system_api_rpc_token_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_system_api_rpc_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_modules_system_api_rpc_token_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeTokenResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_modules_system_api_rpc_token_proto protoreflect.FileDescriptor

const file_modules_system_api_rpc_token_proto_rawDesc = "" +
	"\n" +
	"\"modules/system/api/rpc/token.proto\x12\x11alexgo.system.rpc\"\x83\x01\n" +
	"\x11IssueTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_type\x18\x02 \x01(\x05R\buserType\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\"{\n" +
	"\x12IssueTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"7\n" +
	"\x12RevokeTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"%\n" +
	"\x13RevokeTokenResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xa6\x02\n" +
	"\fTokenService\x12Y\n" +
	"\n" +
	"IssueToken\x12$.alexgo.system.rpc.IssueTokenRequest\x1a%.alexgo.system.rpc.IssueTokenResponse\x12]\n" +
	"\fRefreshToken\x12&.alexgo.system.rpc.RefreshTokenRequest\x1a%.alexgo.system.rpc.IssueTokenResponse\x12\\\n" +
	"\vRevokeToken\x12%.alexgo.system.rpc.RevokeTokenRequest\x1a&.alexgo.system.rpc.RevokeTokenResponseB%Z#alexGo-cloud/modules/system/api/rpcb\x06proto3"

var (
	file_modules_system_api_rpc_token_proto_rawDescOnce sync.Once
	file_modules_system_api_rpc_token_proto_rawDescData []byte
)

func file_modules_system_api_rpc_token_proto_rawDescGZIP() []byte {
	file_modules_system_api_rpc_token_proto_rawDescOnce.Do(func() {
		file_modules_system_api_rpc_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_system_api_rpc_token_proto_rawDesc), len(file_modules_system_api_rpc_token_proto_rawDesc)))
	})
	return file_modules_system_api_rpc_token_proto_rawDescData
}

var file_modules_system_api_rpc_token_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modules_system_api_rpc_token_proto_goTypes = []any{
	(*IssueTokenRequest)(nil),   // 0: alexgo.system.rpc.IssueTokenRequest
	(*IssueTokenResponse)(nil),  // 1: alexgo.system.rpc.IssueTokenResponse
	(*RefreshTokenRequest)(nil), // 2: alexgo.system.rpc.RefreshTokenRequest
	(*RevokeTokenRequest)(nil),  // 3: alexgo.system.rpc.RevokeTokenRequest
	(*RevokeTokenResponse)(nil), // 4: alexgo.system.rpc.RevokeTokenResponse
}
var file_modules_system_api_rpc_token_proto_depIdxs = []int32{
	0, // 0: alexgo.system.rpc.TokenService.IssueToken:input_type -> alexgo.system.rpc.IssueTokenRequest
	2, // 1: alexgo.system.rpc.TokenService.RefreshToken:input_type -> alexgo.system.rpc.RefreshTokenRequest
	3, // 2: alexgo.system.rpc.TokenService.RevokeToken:input_type -> alexgo.system.rpc.RevokeTokenRequest
	1, // 3: alexgo.system.rpc.TokenService.IssueToken:output_type -> alexgo.system.rpc.IssueTokenResponse
	1, // 4: alexgo.system.rpc.TokenService.RefreshToken:output_type -> alexgo.system.rpc.IssueTokenResponse
	4, // 5: alexgo.system.rpc.TokenService.RevokeToken:output_type -> alexgo.system.rpc.RevokeTokenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_system_api_rpc_token_proto_init() }
func file_modules_system_api_rpc_token_proto_init() {
	if File_modules_system_api_rpc_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_system_api_rpc_token_proto_rawDesc), len(file_modules_system_api_rpc_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_system_api_rpc_token_proto_goTypes,
		DependencyIndexes: file_modules_system_api_rpc_token_proto_depIdxs,
		MessageInfos:      file_modules_system_api_rpc_token_proto_msgTypes,
	}.Build()
	File_modules_system_api_rpc_token_proto = out.File
	file_modules_system_api_rpc_token_proto_goTypes = nil
	file_modules_system_api_rpc_token_proto_depIdxs = nil
}
