apiVersion: v1
kind: ConfigMap
metadata:
  name: alexgo-config
  namespace: alexgo-cloud
data:
  HTTP_ADDR: ":8080"
  DB_DSN: "root:password@tcp(mysql.alexgo-cloud.svc.cluster.local:3306)/alexgo?charset=utf8mb4&parseTime=True&loc=Local"
  config.yaml: |
    server:
      http_addr: ":8080"
    database:
      dsn: "root:password@tcp(mysql.alexgo-cloud.svc.cluster.local:3306)/alexgo?charset=utf8mb4&parseTime=True&loc=Local"
    migrate:
      auto: true
    microservice:
      enabled: false
      registry: "consul://127.0.0.1:8500"
    modules:
      system: true
      order: true

