apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alexgo-ingress
  namespace: alexgo-cloud
spec:
  rules:
    - host: alexgo.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alexgo-server
                port:
                  number: 8080

